CREATE TABLE GAMES
(
    NAME VARCHAR2(20)
    , AGEMIN NUMBER NOT NULL
    , AGEMAX NUMBER NOT NULL
    , PLAYERSMIN NUMBER NOT NULL
    , PLAYERSMAX NUMBER NOT NULL
    , DURATION NUMBER NOT NULL
);

INSERT INTO GAMES (NAME, AGEMIN, AGEMAX, PLAYERSMIN, PLAYERSMAX, DURATION) VALUES ('Monopoly', '5', '10', '2', '5', '60');
INSERT INTO GAMES (NAME, AGEMIN, AGEMAX, PLAYERSMIN, PLAYERSMAX, DURATION) VALUES ('Uno', '3', '80', '2', '8', '25')

