CREATE TABLE GAMES
(
    NAME VARCHAR2(20)
    , AGEMIN NUMBER NOT NULL
    , AGEMAX NUMBER NOT NULL
    , PLAYERSMIN NUMBER NOT NULL
    , PLAYERSMAX NUMBER NOT NULL
    , DURATION NUMBER NOT NULL
);
